### PR TITLE
WIP - Adding support to tests 

### PR DESCRIPTION
**Pull request by mauricioborges**
Hi there!

In fact I've created this PR more like a way to get in touch with you folks :)

I've started a project of creating a GUI interface for Menge using QT for educational purposes, however I felt that I was not very comfortable with the code yet so I'm creating some characterization tests.

I've used Google Test so far, and I've created a root level CMakeFile.

I need to write some README.md as well

---
This change is [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)

### CODE REVIEW

**Comment by curds01** [comment]
Thanks for contributing! Always happy to welcome someone to the Menge family.

I'm going to take a look at this later today and I'll get back to you.

**Comment by curds01** [comment]
By the way, you might want to check *this* out:

https://github.com/curds01/MengeConfig

If you want to pool our resources on this, I'd be totally down with that.

**Comment by curds01** [comment]
Sorry for the delay -- I keep meaning to get to this. This inspired some house cleaning that ended up larger than I'd expected. This is the very next thing on my todo. I'm eager to start adding unit tests.

**Comment by MengeCrowdSim** [comment]
This is outstanding work you've done here. The reason Menge hasn't previously had tests is that I'm not overly familiar with cmake and getting tests integrated into the code base. So, I've made a number of questions/comments below exposing that ignorance and hoping to strike up some conversations.

If you don't have ready answers for the questions, that's alright. We can defer the answers as we work with it and figure things out.

I'm so looking forward to getting meaningful testing into Menge. And I'm looking forward to working with you on improving Menge.

(BTW, I've enabled reviewable for Menge. I highly recommend it as a much more amenable mechanism for conducting code reviews. The PR should have a link in the opening comment you can click on to access it.)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.gitignore, line 1 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyPrlB7OoeGk4LJ_F-:-LDyPrlB7OoeGk4LJ_F0:b-51vvc5) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/.gitignore#L1)):*
> ```
> cmake-build-debug
> ```

Where does this path come from?

---

*[.gitignore, line 40 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyPadc0-oUGIGbST2z:-LDyPadc0-oUGIGbST3-:b-93ddrz) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/.gitignore#L40)):*
> ```
> *.dll
> 
> # Fortran module files
> ```

Can you explain the origin of all these entries?  Some of them seem relevant, some don't belong at all (like the fortran module files). I'd rather not just include things *en masse*, but make sure that everything added here has an explicit purpose. In other words, if I were to remove a line, I *should* be affected. And right now, I'm not believing it.

---

*[CMakeLists.txt, line 1 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDySG_0D_dGcEk2YVk4:-LDySG_0D_dGcEk2YVk5:b-fa6euj) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/CMakeLists.txt#L1)):*
> ```CMake
> cmake_minimum_required(VERSION 2.8)
> ```

I'd like to talk about this file; I've gone out of my way to put all build infrastructure in the projects directory. This has now leaked out. Can we put it in `/projects/g++`?  What I'd *prefer* is something along the lines of '/projects/g++/testing' (in parallel with `/projects/g++/Menge` and `/projects/g++/Plugins`. And then we can simply modify the `Makefile` in the root to invoke the appropriate cmake apparatus.

That said, I'm open to alternatives. I'd just like to hear the reasons for this file located here.

---

*[src/Menge/MengeCore/PluginEngine/ElementDatabase.h, line 188 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyTBTw6vTVTmjPKczR:-LDyTBTw6vTVTmjPKczS:buopplx) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/Menge/MengeCore/PluginEngine/ElementDatabase.h#L188)):*
> ```objc
> 
> 	template < class Factory, class Element >
> 		void ElementDB< Factory, Element >::addBuiltins() {}
> ```

Looks like this accidentally crept into the PR. Should probably remove it.

---

*[src/test/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyTNmn3AuRG-DzZ_60:-LDyTNmn3AuRG-DzZ_61:b-czw4wg) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/CMakeLists.txt#L12)):*
> ```CMake
>     gtest
>      URL https://github.com/google/googletest/archive/release-1.8.0.zip
> #    URL https://github.com/google/googletest/archive/master.zip
> ```

BTW We don't want to include commented out lines without some documentation *why* we're including it. Otherwise, just delete it.

---

*[src/test/CMakeLists.txt, line 47 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyVBlWCiG2YzwmLjj6:-LDyVBlWCiG2YzwmLjj7:b-778wz) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/CMakeLists.txt#L47)):*
> ```CMake
> 
> 
> add_subdirectory(MengeCore)
> ```

BTW This is great.  Ultimately, the contents of the `test` directory will mirror that of the `Menge` directory where tests will be located in a parallel directory from the units they test.

---

*[src/test/MengeCore/CMakeLists.txt, line 3 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyValz9s_M4O6Def99:-LDyValz9s_M4O6Def9A:b-s82ix2) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/MengeCore/CMakeLists.txt#L3)):*
> ```CMake
> file(GLOB SRCS *.cpp)
> 
> ADD_EXECUTABLE(mengeCoreTest ${SRCS})
> ```

I must admit my ignorance. This looks like it'll accumulate all tests into one giant executable. In my limited experience, I've seen each .cpp file go into its own test so that they can be executed more easily  in parallel for CI.

Thoughts?

---

*[src/test/MengeCore/first.cpp, line 6 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyW1-ABmVKppaTib7u:-LDyW1-B4sDGlw54TKyZ:b-bfxein) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/MengeCore/first.cpp#L6)):*
> ```cpp
> #include "gtest/gtest.h"
> #include "gmock/gmock.h"
> #include "../../Menge/MengeCore/Runtime/SimulatorDB.h"
> ```

I'd much rather see the cmake file modified to include the Menge source directory so that these includes look like:

```c++
#include "Menge/MengeCore/Runtime/SimulatorDB.h"
#include "Menge/MengeCore/PluginEngine/CorePluginEngine.h"
```

---

*[src/test/MengeCore/first.cpp, line 9 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyWU4FBafry8JPSqQh:-LDyWU4FBafry8JPSqQi:byu4g05) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/MengeCore/first.cpp#L9)):*
> ```cpp
> #include "../../Menge/MengeCore/PluginEngine/CorePluginEngine.h"
> #include "MengeVis/SceneGraph/GLScene.h"
> ```

BTW I'm pushing Menge to be compliant with the google styleguide. I have a PR waiting in the wings that will update a lot of the formatting of Menge and include a `clang-format` configuration. This will probably land first, and I'll just add this file to the PR that updates formatting.

---

*[src/test/MengeCore/first.cpp, line 31 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyWjjq1JOD_j4JdBAA:-LDyWjjq1JOD_j4JdBAB:b-x6gaqm) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/MengeCore/first.cpp#L31)):*
> ```cpp
> 
> };
> ```

These tests should get some `//` documentation to explain their purpose and, as necessary, how they go about achieving that purpose (if the code doesn't speak clearly for itself).

---

*[src/test/MengeCore/first.cpp, line 56 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyWtMh6bv9ZChVRlrh:-LDyWtMh6bv9ZChVRlri:b-o3co99) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/MengeCore/first.cpp#L56)):*
> ```cpp
> 
> 
>     const std::string &behaveFile = "/home/mauricio/dev/Menge/examples/core/4square/4squareB.xml";
> ```

We'll have to fix these paths. Obviously, these tests won't pass for anyone else.

---

*[src/test/MengeCore/first.cpp, line 64 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyX7OpE7jFJixmbeIY:-LDyX7OpE7jFJixmbeIZ:b1kz15o) ([raw file](https://github.com/mengecrowdsim/menge/blob/57dcf6a96edb8e4fa8fc216eff257d0e36831650/src/test/MengeCore/first.cpp#L64)):*
> ```cpp
>                                                                      scbVersion, VERBOSE);
> 
>     EXPECT_FALSE(sim == 0x00);
> ```

We're modernizing Menge's C++ and prefer `nullptr` to `0x00` going forward.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92#-:-LDyXKUj-Q4Hx9Zke5UJ:bfco0tf)*

**Comment by mauricioborges** [comment]
hello there! Sorry, I was a bit offline lately, but now I'll jump back here.  Soon I'll reply to your comments

**Comment by mauricioborges** [comment]
@curds01 about this repository https://github.com/curds01/MengeConfig. Have you built it in VisualStudio? I believe it just works there right?

**Comment by mauricioborges** [comment]
Review status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @MengeCrowdSim, @mauricioborges, and @curds01)

---

*[src/test/MengeCore/first.cpp, line 9 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyWU4FBafry8JPSqQh:-LEle-Ff0zDDjqMmn-aI:b-5ct0gz) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/src/test/MengeCore/first.cpp#L9)):*
<details><summary><i>Previously, MengeCrowdSim (Menge crowd simulation) wrote…</i></summary><blockquote>

BTW I'm pushing Menge to be compliant with the google styleguide. I have a PR waiting in the wings that will update a lot of the formatting of Menge and include a `clang-format` configuration. This will probably land first, and I'll just add this file to the PR that updates formatting.
</blockquote></details>

awesome! 

---

*[src/test/MengeCore/first.cpp, line 64 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyX7OpE7jFJixmbeIY:-LEldf2x7L374eNzPBn3:b-896fix) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/src/test/MengeCore/first.cpp#L64)):*
<details><summary><i>Previously, MengeCrowdSim (Menge crowd simulation) wrote…</i></summary><blockquote>

We're modernizing Menge's C++ and prefer `nullptr` to `0x00` going forward.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)*

**Comment by mauricioborges** [comment]
Review status: 7 of 9 files reviewed, 9 unresolved discussions (waiting on @MengeCrowdSim, @mauricioborges, and @curds01)

---

*[src/test/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyTNmn3AuRG-DzZ_60:-LElfEso8l1CifuurK9G:b-7rl0kd) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/src/test/CMakeLists.txt#L12)):*
<details><summary><i>Previously, MengeCrowdSim (Menge crowd simulation) wrote…</i></summary><blockquote>

BTW We don't want to include commented out lines without some documentation *why* we're including it. Otherwise, just delete it.
</blockquote></details>

done

---

*[src/Menge/MengeCore/PluginEngine/ElementDatabase.h, line 188 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyTBTw6vTVTmjPKczR:-LElfKXz8svZaaj9EpWV:bb7f2mf) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/src/Menge/MengeCore/PluginEngine/ElementDatabase.h#L188)):*
<details><summary><i>Previously, mauricioborges (Mauricio Borges Silva) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)*

**Comment by MengeCrowdSim** [comment]
Correct; MengeConfig is currently only set up for windows.

**Comment by mauricioborges** [comment]
Review status: 7 of 9 files reviewed, 9 unresolved discussions (waiting on @MengeCrowdSim, @mauricioborges, and @curds01)

---

*[CMakeLists.txt, line 1 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDySG_0D_dGcEk2YVk4:-LGLxeu13tsqxo0c67NI:bkiys8w) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/CMakeLists.txt#L1)):*
<details><summary><i>Previously, mauricioborges (Mauricio Borges Silva) wrote…</i></summary><blockquote>

So, I've created this file here because that's what I'm more used to (in other languages actually, I'm a very beginner in C++).  But I can adapt it to use the current pattern, is not a problem for me at all. In fact I've seen both approaches in C++ community but I can't find a pattern). Accepted suggestion indeed, will do that
</blockquote></details>

so, in fact I agree on keeping the current structure. I'm quite newbie to cmake and c++ universe (way more used to Java), but I prefer to keep your code style. The only reason I put that there was because it was how I was able to make it work at the time :P. But now I'm back to this effort and I'll refactor it to follow the `projects` folder pattern

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)*

**Comment by mauricioborges** [comment]
Review status: 6 of 9 files reviewed, 9 unresolved discussions (waiting on @MengeCrowdSim, @mauricioborges, and @curds01)

---

*[.gitignore, line 40 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyPadc0-oUGIGbST2z:-LGM-B0UBpde7Uy36hsC:b-896fix) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/.gitignore#L40)):*
<details><summary><i>Previously, mauricioborges (Mauricio Borges Silva) wrote…</i></summary><blockquote>

I should admit I used the gitignore file that Github has for C++ (https://github.com/github/gitignore/blob/master/C%2B%2B.gitignore). However I agree with your approach, will rebase it and only add the files I have locally (by the way I use Intellij CLion what may have created a different set of files locally)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)*

**Comment by mauricioborges** [comment]
Review status: 6 of 9 files reviewed, 9 unresolved discussions (waiting on @MengeCrowdSim, @mauricioborges, and @curds01)

---

*[src/test/MengeCore/first.cpp, line 31 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyWjjq1JOD_j4JdBAA:-LGM-jE57XYaGIDGFW6I:b-896fix) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/src/test/MengeCore/first.cpp#L31)):*
<details><summary><i>Previously, mauricioborges (Mauricio Borges Silva) wrote…</i></summary><blockquote>

oh, my mistake. it was actually my way to see how the original method was  defined. I can remove this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)*

**Comment by mauricioborges** [comment]
Just added some travis-ci support. I decided for that because circleci doesn't support C++ b default

**Comment by mauricioborges** [comment]
Review status: 1 of 9 files reviewed, 9 unresolved discussions (waiting on @MengeCrowdSim, @mauricioborges, and @curds01)

---

*[src/test/CMakeLists.txt, line 47 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyVBlWCiG2YzwmLjj6:-LGO-o7Q2OtzBDjjbz2p:b-dzjn1a) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/src/test/CMakeLists.txt#L47)):*
<details><summary><i>Previously, MengeCrowdSim (Menge crowd simulation) wrote…</i></summary><blockquote>

BTW This is great.  Ultimately, the contents of the `test` directory will mirror that of the `Menge` directory where tests will be located in a parallel directory from the units they test.
</blockquote></details>

I've seen you done the same for the source code as well. Neat!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)*

**Comment by mauricioborges** [comment]
Review status: 1 of 9 files reviewed, 9 unresolved discussions (waiting on @MengeCrowdSim, @mauricioborges, and @curds01)

---

*[src/test/MengeCore/first.cpp, line 6 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/92#-LDyW1-ABmVKppaTib7u:-LGO0-6G0zKzh8Gk0IxQ:b-896fix) ([raw file](https://github.com/mengecrowdsim/menge/blob/dedcb3195425c2b26628b91b91b5c1004c818d80/src/test/MengeCore/first.cpp#L6)):*
<details><summary><i>Previously, mauricioborges (Mauricio Borges Silva) wrote…</i></summary><blockquote>

will do. in fact looks better
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/92)*

**Comment by mauricioborges** [comment]
awesome! hey, what about creating the travis-ci configuration when we have some tests? I'll start creating some tests soon.

**Comment by MengeCrowdSim** [comment]
I was thinking the same -- since you've created the link on the readme; it's about time to connect it.

**Pull request merged**
